### ISSUE TITLE
Minor visual bug when picking up items

### ISSUE THREAD

**Issue by Nwago-Dev** [Wakaba2/World-Renderer#5]
I've rendered multiple planes with different opacities to create a fog effect, which works perfectly, but it creates this flash of orange whenever I pick up an item while looking down.
![I Hate Wandering Trader Sounds](https://github.com/Sumeshi2/World-Renderer/assets/84010841/d3a6ff65-35a6-44b6-943f-6dc59cf5671e)

All I can assume is that for some reason, the orange planes render in front of the actual level when that is happening.

**Comment by Sumeshi2** [comment]
Enable depth test and depth mask before rendering.

**Comment by Nwago-Dev** [comment]
This fixed my issue, thank you.
