### ISSUE TITLE
Lag spikes after pausing for extended amounts of time in dimensions where world renderer is setup. Leak?

### ISSUE THREAD

**Issue by Nwago-Dev** [Wakaba2/World-Renderer#9]
Hello!
I've noticed that pausing my game for a long while will cause the game to freeze for a bit when I eventually unpause it.

The lag spike too is longer, depending on how much time I let the game paused for.

This only happens in dimensions where I've setup world renderer.

I've tested this by adding dimension Surface with effect type Overworld special fog set to false. (Without configuring anything else)
Doing so will cause the game to lag spike when unpaused.
I've then tested it again in the same world, but removed the setup for Surface. The lag spike was gone.

**Comment by Wakaba2** [comment]
Could you tell me MCreator and Forge version?

**Comment by Nwago-Dev** [comment]
MCreator Version 2024.2, using 1.20.1 Generator (47.3.0)
Plugin Version 1.8.1

**Comment by Wakaba2** [comment]
I cannot detect the bug so far. Try downloading the plugin again.

**Comment by Nwago-Dev** [comment]
I've downloaded the plugin and MCreator again, problem still persists.

After creating a new workspace, I discovered the Issue is linked to Graphics - Compute light color.

You need both it and a dimension set up for the game to start spiking.

Here is the settings I used to recreate it in a brand new workspace, 2024,2 1.20.1

![image](https://github.com/user-attachments/assets/51d52488-3f20-4469-bb09-cb7aa8b6f47d)

![image](https://github.com/user-attachments/assets/6a28b663-4ed7-431d-bdf6-27a5536d7bdf)

Doing this will cause the spikes to happen in the overworld.

**Comment by Wakaba2** [comment]
I think v1.8.2 fixed it. Try it again.

**Comment by Nwago-Dev** [comment]
Updated to 1.8.2, bug is still present and doesn't seem to have changed sadly.

**Comment by Nwago-Dev** [comment]
Deleted all the procedures and remade them, the bug seems to be gone now on 1.8.2! The code probably wasn't updating.
Thank you!
